default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: rails-watch-list_development
  username: rails-watch-list
  password: <%= ENV['RAILS-WATCH-LIST_DATABASE_PASSWORD'] %>


test:
  <<: *default
  database: rails-watch-list_test
  username: rails-watch-list
  password: <%= ENV['RAILS-WATCH-LIST_DATABASE_PASSWORD'] %>

production:
  <<: *default
  database: rails-watch-list_production
  username: rails-watch-list
  password: <%= ENV['RAILS-WATCH-LIST_DATABASE_PASSWORD'] %>
```
